### ISSUE TITLE
Landmine Placement

### ISSUE THREAD

**Issue by DolphinDTM** [zardoru/iBMSC#6]
self-explanatory

**Comment by zardoru** [comment]
Note: Control adds Hidden notes, Shift does long notes.

**Comment by DolphinDTM** [comment]
Shift+Ctrl+Click? That or a toggle to change Ctrl+Click to place landmines instead of hidden notes.

**Comment by zardoru** [comment]
Alt + Click?

**Comment by DolphinDTM** [comment]
That could work, not sure if alt+click does some stupid magic shit in windows or not.

**Comment by zardoru** [comment]
Done.
