### ISSUE TITLE
ogg keysounds play back a x2 speed

### ISSUE THREAD

**Issue by DolphinDTM** [zardoru/iBMSC#8]
just wtf.
wav keysounds are not affected.

**Comment by zardoru** [comment]
Post the body and chart please. I didnt find this issue with what i had

**Comment by DolphinDTM** [comment]
http://starkey.ivory.ne.jp/bts/bts/detail/view/7/
http://qstol.info/events/venue/detail?event=3&id=10
any chart

**Comment by DolphinDTM** [comment]
actually just doublechecked the playback speed and its not x2 but x1.5
i still have no idea why this would happen.

**Comment by zardoru** [comment]
did you open a chart after another one? May be a sample rate mismatch

double time

**Comment by DolphinDTM** [comment]
it happened on the first chart i tried.  
opening different charts on the same session does not yield any different results.

**Comment by zardoru** [comment]
It still can be a sample rate mismatch, I will check that

**Comment by zardoru** [comment]
Should be fixed after last commit.
